### ISSUE TITLE
Faulty codepoints mentioned at ligatures

### ISSUE THREAD

**Issue by egmontkob** [OldHungarian/OldHungarian.github.io#2]
Both the Hungarian and English homepages say that the W ligature is achieved using `U+10C93(V) + U+200D + U+10CA5(V)`. The Unicode values shown here correspond to the X (K + Sz) ligature instead.

**Comment by sztupy** [comment]
fixed in https://github.com/OldHungarian/OldHungarian.github.io/commit/75f0b72017a56a6f7d89180199270b233e6167b7

**Comment by egmontkob** [comment]
Köszi! :)
